posts/blueprint.py
from flask import Blueprint, render_template, request, redirect, url_for
from models import Post, Tag
from posts.forms import PostForm
from app import db
from flask_security import login_required

posts = Blueprint('posts', __name__, template_folder='templates')


'''
@posts.route('/create', methods=['POST', 'GET'])
@login_required
def create_post():
    if request.method == 'POST':
        title = request.form['title']
        body = request.form['body']

        try:
            post = Post(title=title, body=body)
            db.session.add(post)
            db.session.commit()
        except:
            print('Не удалось записать в базу данных')
        return redirect(url_for('posts.index'))

    form = PostForm()
    return render_template('posts/create_post.html', form=form)


@posts.route('/<slug>/edit/', methods=['POST', 'GET'])
@login_required
def edit_post(slug):
    post = Post.query.filter(Post.slug == slug).first_or_404()

    if request.method == 'POST':
        form = PostForm(formdata=request.form, obj=post)
        form.populate_obj(post)
        db.session.commit()

        return redirect(url_for('posts.post_detail', slug=post.slug))

    form = PostForm(obj=post)
    return render_template('posts/edit_post.html', post=post, form=form)
'''


@posts.route('/')
def index():
    q = request.args.get('q')

    page = request.args.get('page')

    if page and page.isdigit():
        page = int(page)
    else:
        page = 1

    if q:
        posts = Post.query.filter(Post.title.contains(q) | Post.body.contains(q))
    else:
        posts = Post.query.order_by(Post.created.desc())

    pages = posts.paginate(page=page, per_page=3)

    return render_template('posts/index.html', pages=pages)


@posts.route('/<slug>')
def post_detail(slug):
    post = Post.query.filter(Post.slug == slug).first_or_404()
    tags = post.tags
    return render_template('posts/post_detail.html', post=post, tags=tags)


@posts.route('/tag/<slug>')
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug == slug).first_or_404()
    posts = tag.posts.all()

    return render_template('posts/tag_detail.html', tag=tag, posts=posts)


@posts.route('/profile')
# @login_required
def profile():
    return render_template('posts/profile.html')

posts/templates/posts/index.html
{% set active_page = "index" %}
{% extends 'base.html' %}

{% block title %}
    The Soil Database
{% endblock %}

{% block content_title %}
    Новости
{% endblock %}

{% block content %}

    <div class="row text-left mt-4 mb-4">
    {% for post in pages.items %}
            <div class="col-xs-12 col-sm-6 col-lg-4">
                <div class="card card-style">
                    <img src="/static/img/post_image/{{ post.path }}" alt="{{ post.path }}">
                    <div class="card-body">
                        <h4 class="card-title">{{ post.title }}</h4>
                        <h6 class="card-subtitle mb-2 text-muted">{{ post.created }}</h6>
                        <p class="card-text">{{ post.short_description }}</p>
                    </div>
                    <a class="btn btn-success" href="{{ url_for('posts.post_detail', slug=post.slug) }}">Перейти</a>
                </div>
            </div>
    {% endfor %}
    </div>

    <nav aria-label="Page navigation example">
        <ul class="pagination">
            <li
                {% if not pages.has_prev %}
                    class="page-item disabled"
                {% endif %}
            >
                <a class="page-link" href="./?page={{ pages.prev_num }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>

            {% for page in pages.iter_pages() %}
                <li {% if page == pages.page %} class="page-item active" {% endif %}>
                    <a class="page-link" href="./?page={{ page }}"> {{ page }}</a>
                </li>
            {% endfor %}

            <li
                {% if not pages.has_next %}
                    class="page-item disabled"
                {% endif %}
            >
                <a class="page-link" href="./?page={{ pages.next_num }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>

{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block content_title %}
    {{ post.title }}
{% endblock %}

{% block content %}
    <div class="tags">
        {% for tag in tags %}
            <a href="{{ url_for('posts.tag_detail', slug=tag.slug) }}">
                <span class="badge badge-primary">{{ tag.name }}</span>
            </a>
        {% endfor %}
    </div>
    <div class="main-content">
        {{ post.body }}
    </div>
{% endblock %}

posts/templates/posts/tag_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ tag.name }}
{% endblock %}

{% block content_title %}
    Posts for "{{ tag.name }}" tag:
{% endblock %}

{% block content %}
    {% for post in posts %}
        <div class="post col-xs-4">
            <a href="{{ url_for('posts.post_detail', slug=post.slug) }}"> {{ post.title }} </a>
        </div>
    {% endfor %}
{% endblock %}